### ISSUE TITLE
Error on import resources blocks scene opening

### ISSUE THREAD

**Issue by kevinbaptist** [rednblackgames/HyperLap2D#22]
When opening a previous scene, editor crashes without any explicit error.

**To Reproduce**
1. Imported a new spine animation (.json file)
2. An error message appears because the png file didn't match the .json file (not same name)
3. Renamed png, atlas and json file to be same name
4. Reimported the new animation
5. Editor crashes
6. Tried to reopen the same scene and keeps crashing the editor without at leasts an error with the cause.

**Expected behavior**
Application should not keep crashing and we should be able to reopen a scene after an error.

**Desktop:**
 - OS: MacOX 10.15
 - HyperLap2D Version 0.0.3

**Stack Trace**
From log files, when opening the "broken" scene:
```
java.lang.RuntimeException: Actor: MenuItem
|  Label: Example1 - [ /Users/(...)/HyperLap2D-Spine/scene/Example1/project.h2d]
|  VisLabel: 
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:132)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:95)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:69)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:352)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:86)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:208)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:114)
	at games.rednblack.editor.Main.main(Main.java:57)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: /Users/(...)/HyperLap2D-Spine/scene/Example1/assets/orig/spine-animations/stretchyman-pro/stretchyman.png
```

Renaming manually in file system the files solved the issue, nevertheless I let you know of this issue so you can have a look.
Thank you.

**Comment by fgnm** [comment]
Ah got it! Indeed, the check and the error message are wrong, only `json` and `atlas` needs to have the same name, `png` can have any name since their reference are stored in `atlas` file, I'll fix that, Thanks!
