### ISSUE TITLE
Imported Animation doesn't appear on right Panel

### ISSUE THREAD

**Issue by kevinbaptist** [rednblackgames/HyperLap2D#23]
I've imported a new spine animation to my projects. No errors were given, but the animation is not visible on right panel (under resources - animations).

**To Reproduce**
1. Import a new spine resource (exported with Spine 3.7)
2. No error displayed. 
3. On right Panel under "resources - animations", the animation doesn't appear.

**Expected behavior**
We should be able to see the new imported animation or an error message should be displayed.

**Desktop:**
 - OS: MacOX 10.15
 - HyperLap2D Version 0.0.3/0.0.4-dev

**Stack trace**
```
Caused by: java.lang.IllegalArgumentException: Named value not found: name
	at com.badlogic.gdx.utils.JsonValue.getString(JsonValue.java:663)
	at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:275)
	at games.rednblack.editor.view.ui.widget.actors.SpineActor.initSkeletonData(SpineActor.java:85)
	at games.rednblack.editor.view.ui.widget.actors.SpineActor.<init>(SpineActor.java:41)
	at games.rednblack.editor.view.ui.box.resourcespanel.draggable.box.SpineResource.<init>(SpineResource.java:48)
```

**Additional context**
The problem is not directly related with editor. It seems Spine changed the JSON format for the skins and using an export from  Spine 3.8 fixes the issue.
Nevertheless, I thought of letting you know of this issue, it would be nice to have some kind of feedback when an animation cannot be loaded to the current Project. Hope it was helpful.
Thank you!

**Comment by fgnm** [comment]
It looks like that Spine runtime isn't backward compatible, I've add a check for this, thanks
