### ISSUE TITLE
Import too big asset throw error

### ISSUE THREAD

**Issue by xerikssonx** [rednblackgames/HyperLap2D#74]
I've tried import resourse and got error:

`java.lang.RuntimeException: Actor: MenuItem
|  Label: mult - [ D:/workspaces/libgdx/Новая папка/Новая папка\mult/project.h2d]
|  VisLabel: 
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:93)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at games.rednblack.editor.Main.main(Main.java:68)
Caused by: java.lang.RuntimeException: Image does not fit within max page width 2048 and X edge padding 2*2: D:/workspaces/libgdx/Новая папка/Новая папка/mult/assets/orig/images/Mossy - TileSet 3584x3584
	at com.badlogic.gdx.tools.texturepacker.MaxRectsPacker.packPage(MaxRectsPacker.java:129)
	at com.badlogic.gdx.tools.texturepacker.MaxRectsPacker.pack(MaxRectsPacker.java:89)
	at com.badlogic.gdx.tools.texturepacker.TexturePacker.pack(TexturePacker.java:173)
	at games.rednblack.editor.proxy.ResolutionManager.rePackProjectImages(ResolutionManager.java:224)
	at games.rednblack.editor.proxy.ResolutionManager.rePackProjectImagesForAllResolutionsSync(ResolutionManager.java:359)
	at games.rednblack.editor.proxy.ProjectManager.loadProjectData(ProjectManager.java:309)
	at games.rednblack.editor.proxy.ProjectManager.openProjectAndLoadAllData(ProjectManager.java:229)
	at games.rednblack.editor.proxy.ProjectManager.openProjectAndLoadAllData(ProjectManager.java:182)
	at games.rednblack.editor.proxy.ProjectManager.openProjectFromPath(ProjectManager.java:172)
	at games.rednblack.editor.view.menu.HyperLap2DMenuBarMediator.lambda$recentProjectItemClicked$3(HyperLap2DMenuBarMediator.java:213)
	at games.rednblack.editor.view.ui.dialog.SaveProjectDialogMediator.handleNotification(SaveProjectDialogMediator.java:51)
	at org.puremvc.java.patterns.observer.Observer.notifyObserver(Observer.java:72)
	at org.puremvc.java.core.View.lambda$notifyObservers$0(View.java:131)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.puremvc.java.core.View.notifyObservers(View.java:131)
	at org.puremvc.java.patterns.facade.Facade.notifyObservers(Facade.java:428)
	at org.puremvc.java.patterns.facade.Facade.sendNotification(Facade.java:386)
	at org.puremvc.java.patterns.facade.Facade.sendNotification(Facade.java:399)
	at games.rednblack.editor.view.menu.HyperLap2DMenuBarMediator.recentProjectItemClicked(HyperLap2DMenuBarMediator.java:213)
	at games.rednblack.editor.view.menu.HyperLap2DMenuBarMediator.handleFileMenuNotification(HyperLap2DMenuBarMediator.java:166)
	at games.rednblack.editor.view.menu.HyperLap2DMenuBarMediator.handleNotification(HyperLap2DMenuBarMediator.java:105)
	at org.puremvc.java.patterns.observer.Observer.notifyObserver(Observer.java:72)
	at org.puremvc.java.core.View.lambda$notifyObservers$0(View.java:131)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.puremvc.java.core.View.notifyObservers(View.java:131)
	at org.puremvc.java.patterns.facade.Facade.notifyObservers(Facade.java:428)
	at org.puremvc.java.patterns.facade.Facade.sendNotification(Facade.java:386)
	at games.rednblack.editor.event.MenuItemListener.changed(MenuItemListener.java:44)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 13 more
`

File and log attached.
[java-hyperlog.txt](https://github.com/rednblackgames/HyperLap2D/files/7482324/java-hyperlog.txt)
![Mossy - TileSet](https://user-images.githubusercontent.com/7081073/140495826-a85f2833-a632-49ca-becd-c1d8922e8668.png)

**Comment by fgnm** [comment]
Yes, you cannot import resources bigger then atlas settings, moreover you'll not be able to use tiles in this format, but needs to split into multiple images before import.
The exception is already fixed in latest snapshots, I highly advice to use snapshots rather then `v0.0.7` as it's quite old now and I'll not be able to fix error in old runtime :)
