### ISSUE TITLE
Crash when updating Skin Composer

### ISSUE THREAD

**Issue by myyk** [rednblackgames/HyperLap2D#90]
**Describe the bug**
I tried to open skin composer, it told me to update, then it just hangs forever.

**To Reproduce**
1. Click 'Window > Skin Composer'
2. See update dialog 
![Screenshot from 2023-11-17 17-42-35](https://github.com/rednblackgames/HyperLap2D/assets/2080820/9e8cc5c0-9836-44e2-a3c8-f5f8a31a49b2)
3. Hangs here ![Screenshot from 2023-11-17 17-45-37](https://github.com/rednblackgames/HyperLap2D/assets/2080820/2e6bbaac-35a7-4f09-b079-57f21e10783c)
4. Error in terminal
```
Exception in thread "pool-4-thread-1" java.lang.ClassCastException: class java.lang.Float cannot be cast to class games.rednblack.h2d.common.network.model.GithubReleaseData (java.lang.Float is in module java.base of loader 'bootstrap'; games.rednblack.h2d.common.network.model.GithubReleaseData is in unnamed module of loader 'app')
        at games.rednblack.editor.plugin.skincomposer.SkinComposerMediator.lambda$handleNotification$2(SkinComposerMediator.java:97)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Expected behavior**
No crash, Skin Composer to update and open.

**Desktop (please complete the following information):**
 - OS: Linux - Ubuntu 22.04
 - HyperLap2D Version - 0.1.4-snapshot - 4f4ee5faf8169d1f7fea0974d5880940c1e0d391

**Comment by myyk** [comment]
Thank you, I can confirm this flow is working for me now.
